apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: "{{ .Values.domainname }}"
      kubernetes.io/ingress.class: nginx
      #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: {{ .Values.frontend.app_name }}-redirect
  namespace: {{ .Values.environment }}-master
spec:
  rules:
  - host: {{ .Values.rootdomainname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.frontend.app_name }}-svc
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
