apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
 name: {{ .Values.backend.app_name }}
 namespace: {{ .Values.environment }}-master
spec:
 minAvailable: 2
 selector:
   matchLabels:
     app: {{ .Values.backend.app_name }}

