apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.app_name }}
  namespace: {{ .Values.environment }}-master
  labels:
    app: {{ .Values.backend.app_name }}
    environment: {{ .Values.environment }}
spec:
  affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.backend.app_name }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.app_name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Values.backend.app_name }}
        image: {{ .Values.backend.repo }}/{{ .Values.backend.tag }}
        envFrom:
        - configMapRef:
            name: {{ .Values.environment }}-{{ .Values.backend.app_name }}-master
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http-web
        

