apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-tetris
  name: tetris
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: react-tetris
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-tetris
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: subnet
                operator: In
                values:
                - private
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                  matchLabels:
                    app: react-tetris
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
      containers:
      - image: "{{ .Values.image }}" 
        name: react-tetris
        command: ["/bin/bash","-c","npm run-script start"]
        resources: {}
status: {}
