apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tic-tac-toe-testrole
  name: testrole
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: tic-tac-toe-testrole
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tic-tac-toe-testrole
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: subnet
                operator: In
                values:
                - private
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                  matchLabels:
                    app: tic-tac-toe-testrole
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
      containers:
      - image: "{{ .Values.image }}" 
        name: tic-tac-toe-testrole
        resources: {}
status: {}
