apiVersion: v1
kind: ServiceAccount
metadata:
 name: aws-s3-sa-1-2
 namespace: {{ .Values.environment }}-master
 annotations:
   eks.amazonaws.com/role-arn: arn:aws:iam::090420481311:role/solgames_eks_s3
