apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.app_name }}
  namespace: {{ .Values.environment }}-master
  labels:
    app: {{ .Values.frontend.app_name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.frontend.frontendreplicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.app_name }}
        environment: {{ .Values.environment }}
    spec:
      serviceAccountName: aws-s3-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: subnet
                operator: In
                values:
                - private
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ .Values.frontend.app_name }}
        image: {{ .Values.frontend.frontendrepo }}:{{ .Values.frontend.frontendtag }}
        envFrom:
        - configMapRef:
            name: {{ .Values.frontend.app_name }}
        imagePullPolicy: Always
        livenessProbe:
            initialDelaySeconds: 60
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
        ports:
        - containerPort: 80
          name: http-web
        readinessProbe:
            initialDelaySeconds: 60
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
