apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.app_name }}
  namespace: {{ .Values.environment }}-master
  labels:
    app: {{ .Values.frontend.app_name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.frontend.frontendreplicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.app_name }}
        environment: {{ .Values.environment }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: subnet
                operator: In
                values:
                - private
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ .Values.frontend.app_name }}
        image: {{ .Values.frontend.frontendrepo }}:{{ .Values.frontend.frontendtag }}
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "2m"
          limits:
            memory: "2Gi"
            cpu: "5m"
        envFrom:
        - configMapRef:
            name: {{ .Values.frontend.app_name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http-web
