apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nftgame
  name: apps
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nftgame
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nftgame
    spec:
      containers:
      - image: "{{ .Values.image }}" 
        name: nftgame
        command: ["/bin/bash","-c","npm run-script start"]
        resources: {}
status: {}
