apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: APP_NAME_PLACEHOLDER
  name: NAMESPACE_PLACEHOLDER
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: APP_NAME_PLACEHOLDER
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: APP_NAME_PLACEHOLDER
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: subnet
                operator: In
                values:
                - private
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                  matchLabels:
                    app: APP_NAME_PLACEHOLDER
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
      containers:
      - image: "{{ .Values.image }}" 
        name: APP_NAME_PLACEHOLDER
        command: ["/bin/bash","-c","npm run-script start"]
        resources: {}
status: {}
