apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nftgame-argo-obj
  namespace: argocd
spec: 
  destination: 
    namespace: apps
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: nftgame
    repoURL: "https://github.com/shishirkh/cc-helm-charts.git"
    targetRevision: HEAD
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
