apiVersion: v1
kind: Service
metadata:
  name: solana
  namespace: solana
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: solana
  type: ClusterIP
status:
  loadBalancer: {}
