apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe
  namespace: solana-games-now
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: tic-tac-toe
  type: ClusterIP
status:
  loadBalancer: {}
