apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.app_name }}
  namespace: {{ .Values.environment }}-master
  labels:
    app: {{ .Values.frontend.app_name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.app_name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Values.frontend.app_name }}
        image: {{ .Values.frontend.repo }}:{{ .Values.frontend.tag }}
        envFrom:
        - configMapRef:
            name: {{ .Values.frontend.app_name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http-web
        

