apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.environment }}-{{ .Values.app_name }}
  labels:
    app: {{ .Values.app_name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
        environment: {{ .Values.environment }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: subnet
                operator: In
                values:
                - private
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ .Values.app_name }}
        image: {{ .Values.socketrepo }}:{{ .Values.socketrepotag }}
        volumeMounts:
        - name: config-ssl-certs
          mountPath: /etc/ssl/certs
        envFrom:
        - configMapRef:
            name: {{ .Values.app_name }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.socket_server_port }}
          name: http-web
      volumes:
        - name: config-ssl-certs
          configMap:
            name: ca-pemstore
  
