apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
  name: {{ .Values.app_name }}-svc
  namespace: {{ .Values.environment }}-{{ .Values.app_name }}
spec:
  ports:
    - port: 80
      targetPort: http-web
      protocol: HTTPS
      name: http
  selector:
    app: {{ .Values.app_name }}
