####Master####
environment: dev
rootdomainname: solgames.fun
domainname: dev.solgames.fun
####Backend App Configuration####
backend:
  ##### Environment Detail####
  app_name: backend
  app_port: 3001
  db_type: pg
  db_port: 5432
  knex_db_type: pg
  db_host: postgre-solgames.cfe1wp4muyzj.ap-south-1.rds.amazonaws.com
  db_username: postgres
  db_password: Devops!1234#
  db_database: solgames
  jwt_secret: secret
  ##### Deployment Details####
  backendreplicas: 2
  ####Image Details####
  backendrepo: dockerghosh/solgames-backend
  backendtag: 0.33
  redis_port: 6379
  redis_host: solgames-redis-dev.egujsn.ng.0001.aps1.cache.amazonaws.com
  redis_password: ""
####Front End App Configuration####
frontend:
  ##### Environment Detail####
  app_name: frontend
  ##### Deployment Details####
  frontendreplicas: 2
  ####Image Details####
  frontendrepo: dockerghosh/solgames-frontend
  frontendtag: 0.100
  aws_access_key_id: ''
  aws_secret_access_key: ''
  aws_region: 'ap-south-1'
  bucket_name: 'solgames-games-data'
  ### it can been production/development. Development will be based on access keys and prodution will be based on IAM profile.
  auth_type: 'dev'
