apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: metaverse
  name: metaverse
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: metaverse
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: metaverse
    spec:
      containers:
      - image: "{{ .Values.image }}" 
        name: metaverse
        command: ["/bin/bash","-c","npm run-script start"]
        resources: {}
status: {}
