apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: airdrop-as-a-service-argo-obj
  namespace: argocd
spec: 
  destination: 
    namespace: airdrop
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: airdrop-as-a-service
    repoURL: "https://github.com/solgames-fun/solgames-argocd.git"
    targetRevision: HEAD
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
