apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: cuberun-testlog-argo-obj
  namespace: argocd
spec: 
  destination: 
    namespace: testlog
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: cuberun-testlog
    repoURL: "https://github.com/solgames-fun/solgames-argocd.git"
    targetRevision: HEAD
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
